language: rust

cache: cargo

matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: stable
      after_success:
        - cargo login $CARGO_TOKEN
        - cargo publish
    - rust: beta
    - rust: nightly
branches:
  only:
    - master