language: rust

rust:
  - stable
  - beta
  - nightly

cache: cargo

matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: stable
      after_success:
        - cargo login $CARGO_TOKEN
        - cargo publish
    - rust: nightly-2018-08-17
      env: CLIPPY_AND_COMPILE_TESTS=YESPLEASE
      script:
        - rustup component add clippy-preview
        - cargo clippy

branches:
  only:
    - master