[package]
name = "rustamodb"
version = "0.0.2"
authors = ["Colin MacRae <cmac4603@users.noreply.github.com>"]
description = "A rust library for AWS DynamoDB."
license = "MIT OR Apache-2.0"

[dependencies]
lazy_static = "1.2.0"
rusoto_core = "0.32.0"
rusoto_dynamodb = "0.32.0"
